# Used rhodyprog4ds repository as a template for setting up the publish file
# Test pull requests without pushing

name: test-build

on:
  pull_request:
    branches: [ main ]
    
    
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    # Build book
    - name: Build the book
      run: |
        jupyter-book build . --builder pdfhtml
        mv _build/pdf/book.pdf _build/html/coursemanual.pdf
        jupyter-book build .
